workflows:

  # ─────────────────────────────────────────────
  # iOS BUILD → App Store
  # ─────────────────────────────────────────────
  ios-release:
    name: iOS Release (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m1    # macOS gratuito no free tier

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.nexcoin.app
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
      node: 18.17.0
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install Node dependencies
        script: npm ci

      - name: Build web app (Vite)
        script: npm run build

      - name: Capacitor sync iOS
        script: npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Set bundle version
        script: |
          BUILD_NUMBER=$PROJECT_BUILD_NUMBER
          agvtool new-version -all $BUILD_NUMBER

      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true    # muda para false se quiser só gerar o IPA
        submit_to_app_store: false    # muda para true para publicar direto


  # ─────────────────────────────────────────────
  # ANDROID BUILD → Google Play
  # ─────────────────────────────────────────────
  android-release:
    name: Android Release (Google Play)
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      android_signing:
        - nexcoin_keystore            # nome do keystore cadastrado no Codemagic
      vars:
        PACKAGE_NAME: "com.nexcoin.app"
      node: 18.17.0
      java: 17

    scripts:
      - name: Install Node dependencies
        script: npm ci

      - name: Build web app (Vite)
        script: npm run build

      - name: Capacitor sync Android
        script: npx cap sync android

      - name: Build Android AAB (Release)
        script: |
          cd android
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal              # internal → alpha → beta → production
        submit_as_draft: true


  # ─────────────────────────────────────────────
  # ANDROID DEBUG APK (sem assinatura – teste)
  # ─────────────────────────────────────────────
  android-debug:
    name: Android Debug APK
    max_build_duration: 30
    instance_type: linux_x2

    environment:
      node: 18.17.0
      java: 17

    scripts:
      - name: Install Node dependencies
        script: npm ci

      - name: Build web app (Vite)
        script: npm run build

      - name: Capacitor sync Android
        script: npx cap sync android

      - name: Build debug APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
