workflows:

  android-debug:
    name: Android Debug APK
    max_build_duration: 30
    instance_type: linux_x2

    environment:
      node: 18.17.0
      java: "17"

    scripts:
      - name: Install Node dependencies
        script: npm ci

      - name: Build web app (Vite)
        script: npm run build

      - name: Capacitor sync Android
        script: npx cap sync android

      - name: Build debug APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

  ios-release:
    name: iOS Release (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.nexcoin.app
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
      node: 18.17.0
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install Node dependencies
        script: npm ci

      - name: Build web app (Vite)
        script: npm run build

      - name: Capacitor sync iOS
        script: npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
