export const AVAILABLE_CRYPTOS = [
  { symbol: 'BTC', name: 'Bitcoin', coinId: 'bitcoin' },
  { symbol: 'ETH', name: 'Ethereum', coinId: 'ethereum' },
  { symbol: 'SOL', name: 'Solana', coinId: 'solana' },
  { symbol: 'BNB', name: 'BNB', coinId: 'binancecoin' },
  { symbol: 'XRP', name: 'Ripple', coinId: 'ripple' },
  { symbol: 'ADA', name: 'Cardano', coinId: 'cardano' },
  { symbol: 'AVAX', name: 'Avalanche', coinId: 'avalanche-2' },
  { symbol: 'DOGE', name: 'Dogecoin', coinId: 'dogecoin' },
  { symbol: 'DOT', name: 'Polkadot', coinId: 'polkadot' },
  { symbol: 'MATIC', name: 'Polygon', coinId: 'matic-network' },
  { symbol: 'LINK', name: 'Chainlink', coinId: 'chainlink' },
  { symbol: 'UNI', name: 'Uniswap', coinId: 'uniswap' },
  { symbol: 'LTC', name: 'Litecoin', coinId: 'litecoin' },
  { symbol: 'ATOM', name: 'Cosmos', coinId: 'cosmos' },
  { symbol: 'XLM', name: 'Stellar', coinId: 'stellar' },
  { symbol: 'TRX', name: 'Tron', coinId: 'tron' },
  { symbol: 'SHIB', name: 'Shiba Inu', coinId: 'shiba-inu' },
  { symbol: 'WBTC', name: 'Wrapped Bitcoin', coinId: 'wrapped-bitcoin' },
  { symbol: 'DAI', name: 'Dai', coinId: 'dai' },
  { symbol: 'LEO', name: 'UNUS SED LEO', coinId: 'leo-token' },
  { symbol: 'USDC', name: 'USD Coin', coinId: 'usd-coin' },
  { symbol: 'TON', name: 'Toncoin', coinId: 'the-open-network' },
  { symbol: 'ETC', name: 'Ethereum Classic', coinId: 'ethereum-classic' },
  { symbol: 'BCH', name: 'Bitcoin Cash', coinId: 'bitcoin-cash' },
  { symbol: 'APT', name: 'Aptos', coinId: 'aptos' },
  { symbol: 'ARB', name: 'Arbitrum', coinId: 'arbitrum' },
  { symbol: 'OP', name: 'Optimism', coinId: 'optimism' },
  { symbol: 'ICP', name: 'Internet Computer', coinId: 'internet-computer' },
  { symbol: 'FIL', name: 'Filecoin', coinId: 'filecoin' },
  { symbol: 'NEAR', name: 'NEAR Protocol', coinId: 'near' },
  { symbol: 'VET', name: 'VeChain', coinId: 'vechain' },
  { symbol: 'ALGO', name: 'Algorand', coinId: 'algorand' },
  { symbol: 'INJ', name: 'Injective', coinId: 'injective-protocol' },
  { symbol: 'AAVE', name: 'Aave', coinId: 'aave' },
  { symbol: 'MKR', name: 'Maker', coinId: 'maker' },
  { symbol: 'GRT', name: 'The Graph', coinId: 'the-graph' },
  { symbol: 'IMX', name: 'Immutable X', coinId: 'immutable-x' },
  { symbol: 'STX', name: 'Stacks', coinId: 'blockstack' },
  { symbol: 'HBAR', name: 'Hedera', coinId: 'hedera-hashgraph' },
  { symbol: 'FTM', name: 'Fantom', coinId: 'fantom' },
  { symbol: 'SAND', name: 'The Sandbox', coinId: 'the-sandbox' },
  { symbol: 'MANA', name: 'Decentraland', coinId: 'decentraland' },
  { symbol: 'AXS', name: 'Axie Infinity', coinId: 'axie-infinity' },
  { symbol: 'XTZ', name: 'Tezos', coinId: 'tezos' },
  { symbol: 'THETA', name: 'Theta Network', coinId: 'theta-token' },
  { symbol: 'EOS', name: 'EOS', coinId: 'eos' },
  { symbol: 'XMR', name: 'Monero', coinId: 'monero' },
  { symbol: 'FLOW', name: 'Flow', coinId: 'flow' },
  { symbol: 'CHZ', name: 'Chiliz', coinId: 'chiliz' },
  { symbol: 'ZEC', name: 'Zcash', coinId: 'zcash' },
  { symbol: 'RUNE', name: 'THORChain', coinId: 'thorchain' },
  { symbol: 'KLAY', name: 'Klaytn', coinId: 'klay-token' },
  { symbol: 'DASH', name: 'Dash', coinId: 'dash' },
  { symbol: 'NEO', name: 'Neo', coinId: 'neo' },
  { symbol: 'IOTA', name: 'IOTA', coinId: 'iota' },
  { symbol: 'QNT', name: 'Quant', coinId: 'quant-network' },
  { symbol: 'EGLD', name: 'MultiversX', coinId: 'elrond-erd-2' },
  { symbol: 'PEPE', name: 'Pepe', coinId: 'pepe' },
  { symbol: 'FET', name: 'Fetch.ai', coinId: 'fetch-ai' },
  { symbol: 'SUI', name: 'Sui', coinId: 'sui' },
  { symbol: 'SEI', name: 'Sei', coinId: 'sei-network' },
  { symbol: 'USDT', name: 'Tether', coinId: 'tether' },
];
